@api_HostAddress = http://localhost:5166

### Get stocks
GET {{api_HostAddress}}/api/stock
Accept: application/json


### Get stock by id
GET {{api_HostAddress}}/api/stock/1
Accept: application/json


### Get stock by id
GET {{api_HostAddress}}/weatherforecast/
Accept: application/json





